spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/myNetwork
    username: ...
    password: ...
  flyway:
    baseline-on-migrate: true
